[package]
name = "yew-sample-app"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
stylist = { version = "0.8.0", features = ["yew_integration"] }
wasm-bindgen = "0.2"
yew = "0.18"
