[tasks.build]
install_crate = "wasm-pack"
command = "wasm-pack"
args = [
  "build",
  "--target",
  "web",
  "--out-name",
  "wasm",
  "--out-dir",
  "./static",
]

[tasks.hot-build]
install_crate = "cargo-watch"
command="cargo"
args=["watch", "-x", "make build"]

[tasks.serve]
install_crate = "miniserve"
command = "miniserve"
args = ["./static", "--index", "index.html"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]
dependencies = ["format"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]
